bitbag_sylius_banner_plugin_ad:
  resource: |
    alias: bitbag_sylius_banner_plugin.ad
    section: admin
    path: /banner/ad
    permission: true
    templates: "@SyliusAdmin\\Crud"
    redirect: update
    grid: bitbag_sylius_banner_plugin_ad
    vars:
        all:
            subheader: bitbag_sylius_banner_plugin.ui.ad
        index:
            icon: 'tags'
  type: sylius.resource

bitbag_sylius_banner_plugin_banner:
  resource: |
    alias: bitbag_sylius_banner_plugin.banner
    section: admin
    path: /banner/banner
    permission: true
    templates: "@SyliusAdmin\\Crud"
    redirect: update
    grid: bitbag_sylius_banner_plugin_banner
    vars:
        all:
            subheader: bitbag_sylius_banner_plugin.ui.banner
            templates:
                form: "@BitBagSyliusBannerPlugin/Banner/_form.html.twig"
        index:
            icon: 'tags'
  type: sylius.resource

bitbag_sylius_banner_plugin_section:
  resource: |
    alias: bitbag_sylius_banner_plugin.section
    section: admin
    path: /banner/section
    permission: true
    templates: "@SyliusAdmin\\Crud"
    redirect: update
    grid: bitbag_sylius_banner_plugin_section
    vars:
        all:
            subheader: bitbag_sylius_banner_plugin.ui.section
        index:
            icon: 'tags'
  type: sylius.resource
