imports:
    - { resource: "@BitBagSyliusBannerPlugin/Resources/config/grids/admin/ad.yaml" }
    - { resource: "@BitBagSyliusBannerPlugin/Resources/config/grids/admin/banner.yaml" }
    - { resource: "@BitBagSyliusBannerPlugin/Resources/config/grids/admin/section.yaml" }
