imports:
    - { resource: "@BitBagSyliusBannerPlugin/Resources/config/services.xml" }
    - { resource: "@BitBagSyliusBannerPlugin/Resources/config/resources.yaml" }
    - { resource: "@BitBagSyliusBannerPlugin/Resources/config/grids/*.yaml" }

parameters:
    bitbag_sylius_banner_plugin.uploader.filesystem: bitbag_sylius_banner_plugin_banner

knp_gaufrette:
    adapters:
        bitbag_sylius_banner_plugin_banner:
            local:
                directory: "%sylius_core.public_dir%"
                create: true
    filesystems:
        bitbag_sylius_banner_plugin_banner:
            adapter: "%bitbag_sylius_banner_plugin.uploader.filesystem%"

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.project_dir%/public"
sylius_ui:
    events:
        sylius.shop.homepage:
            blocks:
                banner:
                    template: "@BitBagSyliusBannerPlugin/Shop/Homepage/_banner.html.twig"
                    priority: 60
                latest_products:
                    template: "@SyliusShop/Homepage/_latestProducts.html.twig"
                    priority: 50
                latest_products_carousel:
                    template: "@SyliusShop/Homepage/_latestProductsCarousel.html.twig"
                    priority: 40
                newsletter:
                    template: "@SyliusShop/Homepage/_newsletter.html.twig"
                    priority: 30
                products_grid:
                    template: "@SyliusShop/Homepage/_productsGrid.html.twig"
                    priority: 20
                about_us:
                    template: "@SyliusShop/Homepage/_aboutUs.html.twig"
                    priority: 10