imports:
    - { resource: "@BitBagSyliusBannerPlugin/Resources/config/services.xml" }
    - { resource: "@BitBagSyliusBannerPlugin/Resources/config/resources.yaml" }
    - { resource: "@BitBagSyliusBannerPlugin/Resources/config/grids/*.yaml" }

parameters:
    bitbag_sylius_banner_plugin.uploader.filesystem: bitbag_sylius_banner_plugin_banner

knp_gaufrette:
    adapters:
        bitbag_sylius_banner_plugin_banner:
            local:
                directory: "%sylius_core.public_dir%"
                create: true
    filesystems:
        bitbag_sylius_banner_plugin_banner:
            adapter: "%bitbag_sylius_banner_plugin.uploader.filesystem%"

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.project_dir%/public"
