bitbag_admin:
    resource: "@BitBagSyliusBannerPlugin/Resources/config/routing/admin.yaml"
    prefix: /admin

bitbag_shop:
    resource: "@BitBagSyliusBannerPlugin/Resources/config/routing/shop.yaml"
    prefix: /{_locale}
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
