sylius_grid:
    grids:
        bitbag_sylius_banner_plugin_banner:
            driver:
                name: doctrine/orm
                options:
                    class: "%bitbag_sylius_banner_plugin.model.banner.class%"
            sorting:
                id: desc
            fields:
                locale.code:
                    type: string
                    label: sylius.ui.locale
                    sortable: ~
                section.name:
                    type: string
                    label: bitbag_sylius_banner_plugin.ui.section
                    sortable: ~

                path:
                    type: string
                    label: bitbag_sylius_banner_plugin.ui.path
                    sortable: ~
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
