bitbag_sylius_banner_plugin_ad:
    resource: |
        alias: bitbag_sylius_banner_plugin.ad
        section: admin
        path: /banner/ad
        permission: true
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: bitbag_sylius_banner_plugin_ad
        vars:
            all:
                subheader: bitbag_sylius_banner_plugin.ui.ad
            index:
                icon: 'tags'
    type: sylius.resource
