bitbag_sylius_banner_plugin_banner:
    resource: |
        alias: bitbag_sylius_banner_plugin.banner
        section: admin
        path: /banner/banner
        permission: true
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: bitbag_sylius_banner_plugin_banner
        vars:
            all:
                subheader: bitbag_sylius_banner_plugin.ui.banner
            index:
                icon: 'tags'
    type: sylius.resource
