name: Coding standard

on:
    push:
        branches-ignore:
            - 'dependabot/**'
    pull_request: ~
    release:
        types: [created]
    workflow_dispatch: ~

jobs:
    tests:
        runs-on: ubuntu-latest

        name: "Sylius ${{ matrix.sylius }}, PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}, 
  MySQL ${{ matrix.mysql }}, State Machine Adapter ${{ matrix.state_machine_adapter }}"

        strategy:
            fail-fast: false
            matrix:
                php: ["8.0", "8.1", "8.2", "8.3"]
                symfony: ["^5.4", "^6.0"]
                sylius: ["~1.12.0", "~1.13.0"]
                node: ["^20.x"]
                mysql: ["8.0"]
                state_machine_adapter: ["winzou_state_machine", "symfony_workflow"]

                exclude:
                    - sylius: "~1.12.0"
                      state_machine_adapter: "symfony_workflow"
                    - sylius: "~1.13.0"
                      php: "8.0"


        env:
            APP_ENV: test
            DATABASE_URL: "mysql://root:root@127.0.0.1/sylius?serverVersion=${{ matrix.mysql }}"

        steps:
            -
                uses: actions/checkout@v2
            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    extensions: intl
                    tools: symfony
                    coverage: none
            -
                name: Get Composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -
                name: Cache Composer
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json **/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-${{ matrix.php }}-composer-
            -
                name: Restrict Symfony version
                if: matrix.symfony != ''
                run: |
                    composer config extra.symfony.require "${{ matrix.symfony }}"
            -
                name: Restrict Sylius version
                if: matrix.sylius != ''
                run: composer require "sylius/sylius:${{ matrix.sylius }}" --no-update --no-scripts --no-interaction

            -
                name: Install PHP dependencies
                run: composer install --no-interaction

            -
                name: Run PHPStan
                run: vendor/bin/phpstan analyse -c phpstan.neon -l 8 src/

            -
                name: Run ECS
                run: vendor/bin/ecs

            -
                name: Failed build Slack notification
                uses: rtCamp/action-slack-notify@v2
                if: ${{ failure() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
                env:
                    SLACK_CHANNEL: ${{ secrets.FAILED_BUILD_SLACK_CHANNEL }}
                    SLACK_COLOR: ${{ job.status }}
                    SLACK_ICON: https://github.com/rtCamp.png?size=48
                    SLACK_MESSAGE: ':x:'
                    SLACK_TITLE: Failed build on ${{ github.event.repository.name }} repository
                    SLACK_USERNAME: ${{ secrets.FAILED_BUILD_SLACK_USERNAME }}
                    SLACK_WEBHOOK: ${{ secrets.FAILED_BUILD_SLACK_WEBHOOK }}
